name: ci

on: push

jobs:
  build:
    name: Build code and run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 15
    container:
      image: ghcr.io/warmosaic/contracts-builder:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: echo "/root/.cargo/bin:/root/.foundry/bin" >> $GITHUB_PATH
      - run: forge install
      - run: pnpm i
      - run: pnpm build
      - run: pnpm test